# Run `conda-env create -f environment.yml`
name: healthmap #Environment name
channels:
  - conda-forge
dependencies:
  - python=3.6
  - plotly
  - geopandas
  - pandas
  - dash
  - dash-renderer
  - dash-core-components
  - dash-html-components
  - numpy
  - matplotlib
  - pip:
    - shapely
    - osmnx
    - networkx
    - gunicorn # for app deployment