name: dash_app #Environment name
dependencies:
  - python=3.8
  - pip:
    - dash
    - dash-renderer
    - dash-core-components
    - dash-html-components
    - plotly
    - osmnx
    - geopandas
    - pandas
    - numpy
    - shapely
    - networkx
    - matplotlib
    - gunicorn # for app deployment